services:
  backend:
    container_name: task_backend_container
    build:
      context: ./
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:tests123@mydb:5432/mydb
    depends_on:
      - db
  
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tests123
      - POSTGRES_DB=mydb
    

# to build the container run : docker compose up --build 
# and to remove : docker compose down